name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: List Repository Files (Debugging)
      run: ls -R  # Check if manage.py exists and where it is located

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Migrations
      run: |
        python manage.py migrate
      working-directory: ./  

    - name: Run Tests
      run: |
        python manage.py test
      working-directory: ./  
